import Head from "next/head";
import { Card } from "../Components";
import { getPosts } from "../services";
import classes from "../styles/Home.module.css";

export default function Home({ posts }) {
	return (
		<div>
			<Head>
				<title>SalmandotBlog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={classes.container}>
				{posts.map((post) => (
					<Card key={post.node.title} post={post.node} />
				))}
			</div>
		</div>
	);
}

export async function getStaticProps() {
	const posts = (await getPosts()) || [];

	return {
		props: { posts },
	};
}
